class BlogModel {
  final String date,
      title,
      description1,
      image,
      ort,
      bild1,
      bild2,
      description2,
      bild3,
      description3,
      bild4,
      bild5,
      description4,
      bild6,
      bild7,
      bild8,
      description5,
      bild9,
      bild10,
      bild11,
      description6,
      description7,
      description8,
      bild12,
      description9,
      bild13,
      description14,
      bild14,
      description10;

  BlogModel({
    this.date,
    this.title,
    this.description1,
    this.image,
    this.ort,
    this.bild1,
    this.bild2,
    this.description2,
    this.bild3,
    this.description3,
    this.bild4,
    this.bild5,
    this.description4,
    this.bild6,
    this.bild7,
    this.bild8,
    this.description5,
    this.description6,
    this.description7,
    this.bild9,
    this.bild10,
    this.bild11,
    this.description8,
    this.bild12,
    this.description9,
    this.bild13,
    this.description14,
    this.bild14,
    this.description10,
  });
}

List<BlogModel> blogPosts = [
  BlogModel(
    ort: "Berlin",
    date: "28 Februar - 10 März 2021",
    image: "assets/images/DAStartbild.PNG",
    title: "Danke Anke",
    description1:
        "Hallo,\n\nnach einer durchwachsenen Nacht begann unser erster Tag um 7 Uhr. Ohne Frühstück im Magen machten wir die Kothaufen der Tiere weg.",
    bild1: "assets/images/Nichts.PNG",
    description2: "",
    bild2: "assets/images/Nichts.PNG",
    bild4: "assets/images/Nichts.PNG",
    bild3: "assets/images/AnkeStall.PNG",
    description3: "",
    bild5: "assets/images/Nichts.PNG",
    description4:
        "Komischerweise war es Anke hier wichtig, dass es wie geleckt aussieht, wohingegen alles andere eher einem „Saustall“ ähnelte. Ob hier etwa jemand die Räumlichkeiten verwechselt hat? Nach einem gemeinsamen Frühstück mit der Verrückten und den anderen Workawayern gingen wir mit Sylvia und dem blinden Hund spazieren, welcher gerne unschuldige Mädchen beißt.",
    bild6: "assets/images/Nichts.PNG",
    bild7: "assets/images/BlinderHund.PNG",
    bild8: "assets/images/Nichts.PNG",
    description5:
        "Danach haben wir Brot von 1749 gesägt, um es später den Tieren zu verfüttern. Ein paar Anschisse später sind wir mit den vier merkwürdigen Eseln spazieren gegangen.",
    bild9: "assets/images/Nichts.PNG",
    description6: "",
    bild10: "assets/images/RentnerEsel.PNG",
    description7:
        "\nAuch ein Eselspaziergang  entspricht hier nicht der Norm. Während alle Workawayer einen Esel zur Hand nahmen, schlappte Anke uns mit ihren ausgelatschten, grünen Crocs hinterher und beschäftigte sich lediglich damit ungefragt Bilder von uns zu machen. Bei Problemen mit den Eseln war Ankes Devise stets:„Lasst sie einfach los!“.\nVom Spaziergang zurück in der Ruine begaben wir uns direkt auf die Suche nach einer neuen Unterkunft in Berlin. Nach dem Motto: „Nicht lang schnacken, Kopf in Nacken“, haben wir uns für den morgigen Tag ein Zimmerchen gebucht. Jetzt sahen wir uns noch einem Problem gegenüber: der großen Beichte. Mit dem Gedanken „Vorbereitung ist alles“ saßen wir, wie zwei Abiturienten vor ihrer mündlichen Prüfung, auf dem Bett und übten unser Geständnis. Der Plan war es, es Anke nach dem letzten Abendmahl zu sagen. Das Abendessen war für uns schlimmer wie jeder Horrorfilm, da Anke dauernd über den morgigen Tag plapperte, an dem wir, für alle die es schon vergessen haben, abreisen möchten. Da wir bei unseren Aussagen natürlich nicht lügen wollten, führte Anke mehr oder weniger ein Selbstgespräch. Das anschließende Geständnis verlief erstaunlicherweise ganz gut. Anke akzeptierte unsere Entscheidung ohne unhöflich oder böse zu werden. Zusammen mit den anderen Workawayern konnten wir nun bei Kaminfeuer und schöner Musik den Abend erleichtert ausklingen lassen.",
    bild11: "assets/images/Nichts.PNG",
    description8:
        "Um das Kaptitel Brandenburg zu beenden packen wir bei diesem Blogbeitrag auch noch den nächsten Morgen dazu. Nachdem wir den anderen noch bei der morgendlichen Stallarbeit geholfen hatten, gönnten wir uns alle zusammen noch ein ausgiebiges Frühstück. Heute ohne Anke, denn diese war leider den ganzen Tag unterwegs. Sylvia, die Nette, bot an uns zum Bahnhof zu bringen. Ein Glück, sonst hätten wir 2 h laufen müssten. Glaubt ihr im Ernst, dass es hier verlässliche Busverbindungen gibt? Ankes Benzinkutschte, mit der uns Sylvia transportierte, setzte dem Horrorcamp Anke noch die Krone auf. Der heiße Ofen hatte weder einen rechten Seitenspiegel, noch eine intakte Windschutzscheibe. Am Bahnhof angekommen verabschiedeten wir uns noch von Sylvia und machten uns auf ins nächste Abenteuer Berlin.\n",
    bild12: "assets/images/SpiegelSelfie.PNG",
    description9:
        "\nDANKE ANKE!\n\nHaltet die Ohren steif!\n\nMacht et jut\nEure Chiara und Linda",
    bild13: "assets/images/Nichts.PNG",
    description14: "",
    bild14: "assets/images/GoodbyeAnke.PNG",
    description10: "",
  ),
  BlogModel(
    ort: "See",
    date: "07 - 09 August 2020",
    image: "assets/images/DAStartbild.PNG",
    title: "Angelcamp",
    description1:
        "Hallo,\n\nnach einer durchwachsenen Nacht begann unser erster Tag um 7 Uhr. Ohne Frühstück im Magen machten wir die Kothaufen der Tiere weg.",
    bild1: "assets/images/Nichts.PNG",
    description2: "",
    bild2: "assets/images/Nichts.PNG",
    bild4: "assets/images/Nichts.PNG",
    bild3: "assets/images/AnkeStall.PNG",
    description3: "",
    bild5: "assets/images/Nichts.PNG",
    description4:
        "Komischerweise war es Anke hier wichtig, dass es wie geleckt aussieht, wohingegen alles andere eher einem „Saustall“ ähnelte. Ob hier etwa jemand die Räumlichkeiten verwechselt hat? Nach einem gemeinsamen Frühstück mit der Verrückten und den anderen Workawayern gingen wir mit Sylvia und dem blinden Hund spazieren, welcher gerne unschuldige Mädchen beißt.",
    bild6: "assets/images/Nichts.PNG",
    bild7: "assets/images/BlinderHund.PNG",
    bild8: "assets/images/Nichts.PNG",
    description5:
        "Danach haben wir Brot von 1749 gesägt, um es später den Tieren zu verfüttern. Ein paar Anschisse später sind wir mit den vier merkwürdigen Eseln spazieren gegangen.",
    bild9: "assets/images/Nichts.PNG",
    description6: "",
    bild10: "assets/images/RentnerEsel.PNG",
    description7:
        "\nAuch ein Eselspaziergang  entspricht hier nicht der Norm. Während alle Workawayer einen Esel zur Hand nahmen, schlappte Anke uns mit ihren ausgelatschten, grünen Crocs hinterher und beschäftigte sich lediglich damit ungefragt Bilder von uns zu machen. Bei Problemen mit den Eseln war Ankes Devise stets:„Lasst sie einfach los!“.\nVom Spaziergang zurück in der Ruine begaben wir uns direkt auf die Suche nach einer neuen Unterkunft in Berlin. Nach dem Motto: „Nicht lang schnacken, Kopf in Nacken“, haben wir uns für den morgigen Tag ein Zimmerchen gebucht. Jetzt sahen wir uns noch einem Problem gegenüber: der großen Beichte. Mit dem Gedanken „Vorbereitung ist alles“ saßen wir, wie zwei Abiturienten vor ihrer mündlichen Prüfung, auf dem Bett und übten unser Geständnis. Der Plan war es, es Anke nach dem letzten Abendmahl zu sagen. Das Abendessen war für uns schlimmer wie jeder Horrorfilm, da Anke dauernd über den morgigen Tag plapperte, an dem wir, für alle die es schon vergessen haben, abreisen möchten. Da wir bei unseren Aussagen natürlich nicht lügen wollten, führte Anke mehr oder weniger ein Selbstgespräch. Das anschließende Geständnis verlief erstaunlicherweise ganz gut. Anke akzeptierte unsere Entscheidung ohne unhöflich oder böse zu werden. Zusammen mit den anderen Workawayern konnten wir nun bei Kaminfeuer und schöner Musik den Abend erleichtert ausklingen lassen.",
    bild11: "assets/images/Nichts.PNG",
    description8:
        "Um das Kaptitel Brandenburg zu beenden packen wir bei diesem Blogbeitrag auch noch den nächsten Morgen dazu. Nachdem wir den anderen noch bei der morgendlichen Stallarbeit geholfen hatten, gönnten wir uns alle zusammen noch ein ausgiebiges Frühstück. Heute ohne Anke, denn diese war leider den ganzen Tag unterwegs. Sylvia, die Nette, bot an uns zum Bahnhof zu bringen. Ein Glück, sonst hätten wir 2 h laufen müssten. Glaubt ihr im Ernst, dass es hier verlässliche Busverbindungen gibt? Ankes Benzinkutschte, mit der uns Sylvia transportierte, setzte dem Horrorcamp Anke noch die Krone auf. Der heiße Ofen hatte weder einen rechten Seitenspiegel, noch eine intakte Windschutzscheibe. Am Bahnhof angekommen verabschiedeten wir uns noch von Sylvia und machten uns auf ins nächste Abenteuer Berlin.\n",
    bild12: "assets/images/SpiegelSelfie.PNG",
    description9:
        "\nDANKE ANKE!\n\nHaltet die Ohren steif!\n\nMacht et jut\nEure Chiara und Linda",
    bild13: "assets/images/Nichts.PNG",
    description14: "",
    bild14: "assets/images/GoodbyeAnke.PNG",
    description10: "",
  ),
  BlogModel(
    ort: "Brandenburg",
    date: "27-28 Februar 2021",
    image: "assets/images/DAStartbild.PNG",
    title: "Danke Anke",
    description1:
        "Hallo,\n\nnach einer durchwachsenen Nacht begann unser erster Tag um 7 Uhr. Ohne Frühstück im Magen machten wir die Kothaufen der Tiere weg.",
    bild1: "assets/images/Nichts.PNG",
    description2: "",
    bild2: "assets/images/Nichts.PNG",
    bild4: "assets/images/Nichts.PNG",
    bild3: "assets/images/AnkeStall.PNG",
    description3: "",
    bild5: "assets/images/Nichts.PNG",
    description4:
        "Komischerweise war es Anke hier wichtig, dass es wie geleckt aussieht, wohingegen alles andere eher einem „Saustall“ ähnelte. Ob hier etwa jemand die Räumlichkeiten verwechselt hat? Nach einem gemeinsamen Frühstück mit der Verrückten und den anderen Workawayern gingen wir mit Sylvia und dem blinden Hund spazieren, welcher gerne unschuldige Mädchen beißt.",
    bild6: "assets/images/Nichts.PNG",
    bild7: "assets/images/BlinderHund.PNG",
    bild8: "assets/images/Nichts.PNG",
    description5:
        "Danach haben wir Brot von 1749 gesägt, um es später den Tieren zu verfüttern. Ein paar Anschisse später sind wir mit den vier merkwürdigen Eseln spazieren gegangen.",
    bild9: "assets/images/Nichts.PNG",
    description6: "",
    bild10: "assets/images/RentnerEsel.PNG",
    description7:
        "\nAuch ein Eselspaziergang  entspricht hier nicht der Norm. Während alle Workawayer einen Esel zur Hand nahmen, schlappte Anke uns mit ihren ausgelatschten, grünen Crocs hinterher und beschäftigte sich lediglich damit ungefragt Bilder von uns zu machen. Bei Problemen mit den Eseln war Ankes Devise stets:„Lasst sie einfach los!“.\nVom Spaziergang zurück in der Ruine begaben wir uns direkt auf die Suche nach einer neuen Unterkunft in Berlin. Nach dem Motto: „Nicht lang schnacken, Kopf in Nacken“, haben wir uns für den morgigen Tag ein Zimmerchen gebucht. Jetzt sahen wir uns noch einem Problem gegenüber: der großen Beichte. Mit dem Gedanken „Vorbereitung ist alles“ saßen wir, wie zwei Abiturienten vor ihrer mündlichen Prüfung, auf dem Bett und übten unser Geständnis. Der Plan war es, es Anke nach dem letzten Abendmahl zu sagen. Das Abendessen war für uns schlimmer wie jeder Horrorfilm, da Anke dauernd über den morgigen Tag plapperte, an dem wir, für alle die es schon vergessen haben, abreisen möchten. Da wir bei unseren Aussagen natürlich nicht lügen wollten, führte Anke mehr oder weniger ein Selbstgespräch. Das anschließende Geständnis verlief erstaunlicherweise ganz gut. Anke akzeptierte unsere Entscheidung ohne unhöflich oder böse zu werden. Zusammen mit den anderen Workawayern konnten wir nun bei Kaminfeuer und schöner Musik den Abend erleichtert ausklingen lassen.",
    bild11: "assets/images/Nichts.PNG",
    description8:
        "Um das Kaptitel Brandenburg zu beenden packen wir bei diesem Blogbeitrag auch noch den nächsten Morgen dazu. Nachdem wir den anderen noch bei der morgendlichen Stallarbeit geholfen hatten, gönnten wir uns alle zusammen noch ein ausgiebiges Frühstück. Heute ohne Anke, denn diese war leider den ganzen Tag unterwegs. Sylvia, die Nette, bot an uns zum Bahnhof zu bringen. Ein Glück, sonst hätten wir 2 h laufen müssten. Glaubt ihr im Ernst, dass es hier verlässliche Busverbindungen gibt? Ankes Benzinkutschte, mit der uns Sylvia transportierte, setzte dem Horrorcamp Anke noch die Krone auf. Der heiße Ofen hatte weder einen rechten Seitenspiegel, noch eine intakte Windschutzscheibe. Am Bahnhof angekommen verabschiedeten wir uns noch von Sylvia und machten uns auf ins nächste Abenteuer Berlin.\n",
    bild12: "assets/images/SpiegelSelfie.PNG",
    description9:
        "\nDANKE ANKE!\n\nHaltet die Ohren steif!\n\nMacht et jut\nEure Chiara und Linda",
    bild13: "assets/images/Nichts.PNG",
    description14: "",
    bild14: "assets/images/GoodbyeAnke.PNG",
    description10: "",
  ),
  BlogModel(
    ort: "Brandenburg",
    date: "26 Februar 2021",
    image: "assets/images/DHCStartbild.PNG",
    title: "Das Horrorcamp",
    description1:
        "Tach och!\n\nNachdem wir uns morgens herzlichst von Sabine und Manfred verabschiedet hatten und sogar ein kleines, süßes Abschiedsgeschenk erhielten, begann ein neues Abenteuer: Brandenburg.",
    bild1: "assets/images/ChiaraKuscheltier.PNG",
    description2: "Die Anfahrt verlief im Großen und Ganzen reibungslos.",
    bild2: "assets/images/LindaBahnhof.PNG",
    bild4: "assets/images/Nichts.PNG",
    bild3: "assets/images/ChiaraSchlaf.PNG",
    description3:
        "Bis auf, dass wir in München fast unseren Zug verpasst haben, aufgrund eines Verkäufers, der den Faultieren bei Zoomania ähnelt, uns einige zum-in-die-Hose-machenden Gestalten begegnet sind und uns Anke (die Lady vom nächsten Stopp) nicht mehr auf unsere Nachrichten antwortete. In Wendisch Riez, einem kleinen Kaff ca. 1,5 h von Berlin entfernt, angekommen, war erstmal keine Anke in Sicht. Doch kurz darauf winkte uns eine junge Frau, welche eindeutig nicht Anke war. Es stellte sich heraus, dass es sich hierbei um Sylvia, einer weiteren Workawayerin aus Spanien, handelt. Zusammen mit ihr und Anke hatten wir eine nette Autofahrt zu unserer zukünftigen Unterkunft. Auf der Fahrt konnten wir noch lachen. Hätten wir nur gewusst was uns erwartet… Im Horrorcamp angekommen, wurden uns nach einigen Strapazen, unsere Zimmer gezeigt. Was sollen wir sagen, liebe Fans, unser Zimmer ähnelte nicht nur, sie war eine Baustelle.",
    bild5: "assets/images/Zimmer1.PNG",
    description4: "",
    bild6: "assets/images/Zimmer2.PNG",
    bild7: "assets/images/Nichts.PNG",
    bild8: "assets/images/Zimmer3.PNG",
    description5: "",
    bild9: "assets/images/Zimmer4.PNG",
    description6: "",
    bild10: "assets/images/Zimmer5.PNG",
    description7:
        "Eine eigene Zimmertür hatten wir natürlich nicht, wer braucht das schon, ein funktionierendes Bad ist doch nur Ballast und Fenster die sich öffnen lassen? Sind wir die Prinzessin auf der Erbse? Wir können doch einfach rausgehen.",
    bild11: "assets/images/Zimmer6.PNG",
    description8:
        "Später kochten wir mit den insgesamt 3 anderen Workawayern (aus Spanien, Italien und Wuppertal) in einer verdreckten Küche, bei der die Spülmaschine nicht ging und der Ofen immer nur ,,crunchy breads“ macht, wie Anke uns ungefähr 43 mal mitteilte. Wir konnten uns mit den anderen zwar nur auf Englisch unterhalten, doch trotzdem waren sie das Highlight dieses Stopps. Nadine, Manuel und Sylvia sind sehr nette, inspirierende und lustige Menschen.\nDoch selbst diese 3 tollen Personen konnten das Schlechte nicht überwiegen. Neben dem bereits Erwähnten gab es noch einige Hundeattacken, komische und unerzogene Tiere und die reinrassige Terroristenziege, wie Anke sie immer liebevoll nannte, die uns fast stündlich versuchte aufzuspießen. Natürlich nicht zu vergessen ist die verrückte Haushexe Anke. Kleiner Sidefact: Wir durften nur zu bestimmten Uhrzeiten duschen und das auch noch in einem Bad, welches nur von Ankes Schlafzimmer aus begehbar war.\nZurück im Baustellenzimmer und das erste Mal zu zweit, warfen wir uns verzweifelte Blicke zu. Was sollen wir sagen liebe Friends, hier ist es einfach scheiße.",
    bild12: "assets/images/Nichts.PNG",
    description9:
        "Also suchten wir direkt am ersten Abend nach Unterkünften für unsere Flucht. Denn eines war klar, vier Wochen bleiben wir hier sicher nicht! Dem morgigen Tag geben wir aber noch eine Chance.\nFortsetzung folgt…",
    bild13: "assets/images/Nichts.PNG",
    description14:
        "Haltet die Ohren steif!\n\nMacht et jut\nEure Chiara und Linda ",
    bild14: "assets/images/Zimmer7.PNG",
    description10: "",
  ),
  BlogModel(
    ort: "Bayern",
    date: "25 Februar 2021",
    image: "assets/images/KamelreitenStartbild.PNG",
    title: "Kamelreiten",
    description1:
        "Mahlzeit,\n\nheute ist unser letzter Tag hier im schönen Bayern. Wie jeden Morgen begannen wir routiniert um 9 Uhr mit unserer Stallrunde. Bald wurden wir jedoch von dem lieben Manfred unterbrochen, welcher uns davon überzeugte mit ihm und den Kamelbabys einen kleinen Trip zu unternehmen. Nachdem wir Shanti und Amira in den Hänger geführt hatten, schwangen wir uns zu dritt in den Vorderraum des Sprinters. Dies ließ Erinnerungen an den allseits vermissten Multipla der Fiorinos erwachen. Das und Gute-Laune-Musik, sowie schönes Wetter machten die Fahrt perfekt. Unser erster Stopp war ein Wertstoffhof. Was wir dort zu suchen hatten, liebe Freunde, darauf kommt ihr nie. Naja was sollen wir sagen, wo soll man sonst zwei jeweils 300kg-schwere Kamelbrocken wiegen. Die beiden wieder eingeladen, ging es noch zwei Halfter für die Schnecken kaufen und danach ab ins Tierheim. Besucht haben wir eine gute Freundin von Manfred und Sabine, die sehnsüchtig darauf wartete die Kamelladys kennenzulernen. Anders als man sich ein Tierheim vorstellt, war es dort sehr schön. Die Tiere hatten sehr viel Platz und es wurde sich mit sehr viel Liebe um die Schlawiner gekümmert. Vor allem die vielen Welpen brachten uns zum dahinschmelzen.\nMittags feilte Linda noch an unserem Gästebucheintrag weiter und Chiara setzte die restliche Stallarbeit fort.",
    bild1: "assets/images/Mist.PNG",
    description2:
        "Nachdem wir die Lämmer fütterten fragte Manfred uns ob wir Lust auf Kamelreiten hätten – und ZACK saß die erste schon oben.",
    bild2: "assets/images/Nichts.PNG",
    bild4: "assets/images/ChiaraReitet.PNG",
    bild3: "assets/images/Nichts.PNG",
    description3:
        "Chiara genoss die Tour auf der Couch mit 4 Beinen, während Linda draußen auf den etwas frecheren, ab und zu mal zuschnappenden Kamelhengst Nojan aufpasste. Als Chiara und Manfred ganz auf sich fokussiert waren, sah sich Linda einem riesen Problem gegenüber. Nojan riss sich los!",
    bild5: "assets/images/PferdfrisstChiara.PNG",
    description4:
        "Anschließend war ein Spaziergang mit den euch bereits bekannten zwei Eseln und dem Frauenheld Solero (Lama) geplant. Nun begann eine Tortur, die man schwer in Worte fassen kann. Wir versuchen es trotzdem:\n\nKeine 10 Meter von der Lama-Oase entfernt begann Solero sich zu versteinern. Kurzer Sidefact, wir befanden uns auf einer suboptimalen Versteinigungsstrecke, der Hauptstraße. Irgendwann löste Chiara Linda vom Tauziehen ab und versuchte ebenfalls ihr Glück. Keine Chance. Solero hatte nur seine 25 paarungsbereite Ladys in seinem Lamakopf.",
    bild6: "assets/images/Nichts.PNG",
    bild7: "assets/images/LamaZaun.PNG",
    bild8: "assets/images/Nichts.PNG",
    description5:
        "Nach etlichen Sprintstarts und Hüpfereien von Chiara neben dem Hengst und unter lautem Lachen von Susan und Linda erklärten wir Solero zum Sieger des Kampfes und kehrten um. Nichts ahnend stellten wir Solero auf der Weide ab. Kaum hatten wir zwei Lamas eingefangen und uns auf den Weg gemacht, fiel der Hohlbirne Susan ein, dass sie doch auch lieber ein Lama statt der zwei Esel mitnehmen möchte. Gerade auf der Höhe der Versteinerung Soleros angekommen, bemerkte Linda einen fast schon gelungenen Ausbruchsversuch seiten des Hengstes. Linda die Sprintkanone rannte los um Solero aufzuhalten. Als sie versuchte ihn zurück in den Stall zu führen verwandelte er sich wieder in eine Statue. Nach langem Hin und Her und einem nassen Fuß (Linda, die Dumpfbacke musste natürlich in Graben fallen), versuchten wir unser Glück erneut. Abgesehen davon, dass Chiara ein kaputtes Lama hatte, welches den ganzen Spaziergang geduckt und paarungsbereit umherlief, war unser letzter Spaziergang mit Susan (reißt morgen ab) sehr schön.",
    bild9: "assets/images/Nichts.PNG",
    description6:
        "Linda’s Herz klopfte bis zum Hals und sie rief um Manfreds Hilfe. Auf den Auftrag Manfreds hin, ihn einfach am Halfter zu nehmen und zurückzuführen, meisterte die Kamelflüsterin auch dieses Problem.",
    bild10: "assets/images/Kamelflüsterin.PNG",
    description7:
        "Später reitete Linda und Chiara, ausgestattet mit einem 2 Meter-Stock, versuchte den Hengst zu bändigen. Puls auf 180.\nVerschnaufpausen haben wir heute in den Keller gesperrt, denn für uns ging es direkt mit einem Eselspaziergang zum Edeka weiter.\nDort besorgten wir ein kleines Abschiedsgeschenk. Auf dem Rückweg wollte Sancho mal wieder nicht das was Chiara wollte, aber das ist ja mittlerweile auch nichts Neues mehr.",
    bild11: "assets/images/EselGassi.PNG",
    description8:
        "Am Abend kassierte diese noch 3 Roundhouse-Kicks von der Kameldame Shanti. Unser Schock des Monats.",
    bild12: "assets/images/LamaSabber.PNG",
    description9:
        "Als dann noch in Mitten des Schocks Andreas, der Österreicher, im Bademantel hereinschneite, war es um uns getan. ( Fragt einfach nicht :D )\nUnseren letzten Abend ließen wir bei einem gemütlichen Beisammensein ausklingen.",
    bild13: "assets/images/Pflugsonnenuntergang.PNG",
    description14: "\n",
    bild14: "assets/images/WeideMond.PNG",
    description10:
        "Seid gespannt wie unsere Reise weitergeht. Wir halten euch auf dem Laufenden.\n\nHaltet die Ohren steif!\n\nPfiat eich (ein letztes Mal)\nEure Chiara und Linda",
  ),
  BlogModel(
    ort: "Bayern",
    date: "22 Februar 2021",
    image: "assets/images/SonnsessionStartbild.PNG",
    title: "Sonnsession",
    description1:
        "MÖP MÖP,\nwir sind's wieder!\n\nNach einem unauffäligen Vormittag, gönnten wir uns eine Sonnsession auf Balkonien.",
    bild1: "assets/images/Balkonien.PNG",
    description2:
        "Währenddessen machten wir uns einige Notizen für den Gästebucheintrag für Sabine und Manfred, denn bald, liebe Leser, ist unser Aufenthalt hier schon wieder vorbei. Zusammen mit Susan und gewappnet mit Karotten und Äpfeln, führten wir unsere Sonnsession auf der Weide der Ponys, Esel und dem Alpakamof Pino fort.",
    bild2: "assets/images/LindafüttertPonys.PNG",
    bild4: "assets/images/ChiaraStaring.PNG",
    bild3: "assets/images/PferdeWeide.PNG",
    description3:
        "So ruhig wie auf Balkonien blieb die Situation nicht, denn die Tiere tobten glücklich über die Weide, überfielen uns auf unserer Picknickdecke und Pino, der normalerweise ruhig und charakterlos auf ein und derselben Stelle steht, jagte sogar den Hund Balu.",
    bild5: "assets/images/PferdfrisstChiara.PNG",
    description4:
        "Anschließend war ein Spaziergang mit den euch bereits bekannten zwei Eseln und dem Frauenheld Solero (Lama) geplant. Nun begann eine Tortur, die man schwer in Worte fassen kann. Wir versuchen es trotzdem:\n\nKeine 10 Meter von der Lama-Oase entfernt begann Solero sich zu versteinern. Kurzer Sidefact, wir befanden uns auf einer suboptimalen Versteinigungsstrecke, der Hauptstraße. Irgendwann löste Chiara Linda vom Tauziehen ab und versuchte ebenfalls ihr Glück. Keine Chance. Solero hatte nur seine 25 paarungsbereite Ladys in seinem Lamakopf.",
    bild6: "assets/images/Nichts.PNG",
    bild7: "assets/images/LamaZaun.PNG",
    bild8: "assets/images/Nichts.PNG",
    description5:
        "Nach etlichen Sprintstarts und Hüpfereien von Chiara neben dem Hengst und unter lautem Lachen von Susan und Linda erklärten wir Solero zum Sieger des Kampfes und kehrten um. Nichts ahnend stellten wir Solero auf der Weide ab. Kaum hatten wir zwei Lamas eingefangen und uns auf den Weg gemacht, fiel der Hohlbirne Susan ein, dass sie doch auch lieber ein Lama statt der zwei Esel mitnehmen möchte. Gerade auf der Höhe der Versteinerung Soleros angekommen, bemerkte Linda einen fast schon gelungenen Ausbruchsversuch seiten des Hengstes. Linda die Sprintkanone rannte los um Solero aufzuhalten. Als sie versuchte ihn zurück in den Stall zu führen verwandelte er sich wieder in eine Statue. Nach langem Hin und Her und einem nassen Fuß (Linda, die Dumpfbacke musste natürlich in Graben fallen), versuchten wir unser Glück erneut. Abgesehen davon, dass Chiara ein kaputtes Lama hatte, welches den ganzen Spaziergang geduckt und paarungsbereit umherlief, war unser letzter Spaziergang mit Susan (reißt morgen ab) sehr schön.",
    bild9: "assets/images/Chiara2Lamas.PNG",
    description6: "",
    bild10: "assets/images/LindaLamaWald.PNG",
    description7: "",
    bild11: "assets/images/Lamagelangweilt.PNG",
    description8: "",
    bild12: "assets/images/LamaWaldSicht.PNG",
    description9:
        "Den Abend ließen wir bei einer spaßigen Runde Siedler von Catan, bei der Chiara komplett ablooste, und einem Gläschen Weißwein ausklingen.",
    bild13: "assets/images/Nichts.PNG",
    description14:
        "Haltet die Ohren steif!\nPfiat eich\n\nEure Chiara und Linda",
    bild14: "assets/images/ChiaraSquad.PNG",
    description10: "",
  ),
  BlogModel(
    ort: "Bayern",
    date: "20 Februar 2021",
    image: "assets/images/RadtourStartbild.PNG",
    title: "Fahrradtour",
    description1:
        "Hallo ihr kleinen Racker,\n\nAn unserem heutigen freien Tag stand eine Radtour nach Neuötting an – ohne sich zu Verfahren wäre das eine Strecke von ca. 30 km.",
    bild1: "assets/images/ChiaraFahrrad.PNG",
    description2: "",
    bild2: "assets/images/Nichts.PNG",
    bild4: "assets/images/LindaFahrrad.PNG",
    bild3: "assets/images/Nichts.PNG",
    description3:
        "Da wir natürlich immer artig aufessen (Chiara mehr oder weniger :P), hatten wir den ganzen Tag strahlenden Sonnenschein und fuhren teilweise im T-Shirt – herrlich! Nicht nur das Wetter, sondern auch die Landschaft, die wir durchquerten, war wunderschön.\n\nSo fuhren wir zu Beginn über hügelige Waldgebiete und später radelten wir an der Inn entlang, bis wir schließlich unseren Zielpunkt Neuötting erreichten.",
    bild5: "assets/images/Neuötting.PNG",
    description4:
        "Die Kleinstadt mit ihren weniger als 9000 Einwohnern kam uns wie eine Weltmetropole vor, da wir so viele Autos und Menschen nun wirklich nicht mehr gewöhnt waren. Uns erwartete eine wunderschöne Altstadt, welche viele leckeraussehende Essensangebote zu bieten hatte.",
    bild6: "assets/images/AltesHaus.PNG",
    bild7: "assets/images/Nichts.PNG",
    bild8: "assets/images/Stirner.PNG",
    description5:
        "Da wir am liebsten Yufka, Pizza, Döner und Tapas gleichzeitig essen wollten, entschieden wir uns nach langem Überlegen für eine riesige Gemüsepizza – richtige Entscheidung!",
    bild9: "assets/images/PizzaNeuötting.PNG",
    description6:
        "Auf dem Rückweg machten wir eine Picknickpause am Fluss und haben köstliche süße Stückchen, die wir uns vorher in der Stadt gekauft hatten, verputzt.",
    bild10: "assets/images/Süßstückle.PNG",
    description7:
        "Danach zog Linda, die Sportskanone Chiara, der lahmen Ente davon. Der Abstand wurde bei einem (nach Chiaras Gefühl) drei km langem, sehr steilen Berg ausgebaut. Während Chiara nach den ersten Metern zu schieben begann und sich zur Hohle in Metterzimmern zurückversetzt sah, raste Linda den Berg hinauf. Chiara merkte wieder, dass sie Fahrradfahren (außer mit dem E-bike) einfach hasst und dies wurde auch nicht wirklich besser, als uns ein ungeplanter Umweg zum nächsten Mount Everest führte, welchen dann sogar die Konditionsqueen Lindi mit Chiara hochschob. Wenigsten bescherte uns der Umweg einen schönen Blick auf die Alpen.",
    bild11: "assets/images/Kreuzung.PNG",
    description8:
        "Fix und fertig kamen wir zu Hause an und schauten dem Muskelkater bereits erwartend entgegen.",
    bild12: "assets/images/Nichts.PNG",
    description9: "Haltet die Ohren steif!\nPfiat eich",
    bild13: "assets/images/Nichts.PNG",
    description14: "Eure Chiara und Linda",
    bild14: "assets/images/LindaPizza.PNG",
    description10: "",
  ),
  BlogModel(
    ort: "Bayern",
    date: "15 Februar 2021",
    image: "assets/images/PartyStartbild.PNG",
    title: "Party",
    description1:
        "Ahoi ihr Partypeople,\n\nSpäter am Tag war Shopping angesagt. Begleitet haben uns die zwei Packesel, sowie die zwei Miniponys – ein ganz normaler Einkauf. Das Ziel war der Miniedeka in Erlbach.\nWährend Chiara draußen Wache stand, deckte uns Linda mit neuen Snacks ein.",
    bild1: "assets/images/PonnySeil.PNG",
    description2:
        "Schnell bildete sich ein Publikum. – ganze 5 fremde Personen auf einem Fleck - wow das haben wir ja seit des Verlassens unserer Hood nicht mehr gehabt. Nach einem leckeren Buttercrossoint, hatten wir genügend Power um auf dem Rückweg ein paar Trab- bzw. Galoppeinheiten einzulegen.",
    bild2: "assets/images/Nichts.PNG",
    bild4: "assets/images/Nichts.PNG",
    bild3: "assets/images/LindaHexe.PNG",
    description3:
        "Später tanzten wir Bolognese durch Susan’s Onlinespanischkurs und sangen zu Faschingslieder wie z.B. „das Fliegerlied“ oder „Fiesta Mexicana“. Susan, die gerade eine Grammatikaufgabe lösen sollte, wollte bestimmt nicht in Grund und Boden versinken. Warum denn auch? Es ist doch das Normalste der Welt, dass eine Hexe, eine Ente, Alladin, Lady Gaga und ein Matrose durchs Bild laufen. Nach einer halben Stunde brach Susan, inzwischen ein Smiley mit Herzaugen und schwarzer Perücke, ihren Kurs ab und gesellte sich zur feiernden Gruppe.",
    bild5: "assets/images/PartyKüche.PNG",
    description4: "",
    bild6: "assets/images/Nichts.PNG",
    bild7: "assets/images/InteressantePose.PNG",
    bild8: "assets/images/Nichts.PNG",
    description5:
        "Der restliche Abend, liebe Partypeople, bleibt unter Verschluss. Mit den Details, dass der Abend für uns um 10 Uhr beendet war und dass jede von uns am nächsten Morgen nur noch eine seiner Adiletten besaß, könnt ihr euch den Rest selbst ausmalen.\nUnd damit verabschieden wir uns wieder.",
    bild9: "assets/images/Nichts.PNG",
    description6: "Haltet die Ohren steif!\nPfiat eich",
    bild10: "assets/images/Nichts.PNG",
    description7: "",
    bild11: "assets/images/Nichts.PNG",
    description8: "",
    bild12: "assets/images/Nichts.PNG",
    description9: "",
    bild13: "assets/images/Nichts.PNG",
    description14: "",
    bild14: "assets/images/Nichts.PNG",
    description10: "",
  ),
  BlogModel(
    ort: "Bayern",
    date: "11 Februar 2021",
    image: "assets/images/APStartbild.PNG",
    title: "Aussichtsplattform",
    description1:
        "Griaß eich,\n\nheute war unser zweiter freier Tag. Begonnen haben wir diesen mit einem flotten Billiard-Duell. Chiara sorgte für musikalische Begleitung.\n\nAuf dem Mittagsprogramm stand ein Schneespaziergang mit Wisp zur Aussichtsplatte Leonberg.\n(Ja, auch hier gibt es ein Leonberg).",
    bild1: "assets/images/LindaGassi.PNG",
    description2:
        "Unser Aufbruch lief nicht so glatt wie die Rutschbahnen um den Hof sind. Als wir bereits die Hauptstraße überquert hatten, schossen uns die zwei Kanonen, Balu und Sepp, hinterher.",
    bild2: "assets/images/Chewbacca.PNG",
    bild4: "assets/images/Nichts.PNG",
    bild3: "assets/images/ZugeschneiterHund.PNG",
    description3:
        "Wir sahen die beiden schon unter dem heranrasendem Auto liegen. Zum Glück hörten sie aufs Wort und folgten uns einvernehmlich die Hofauffahrt hinauf.\nAls es dann endlich losgehen konnte, erwartete uns eine Welt wie im Märchen. Die beeindruckende Landschaft mit dem glitzernden Schnee, die Ruhe und die ab und zu vorbei spazierenden Rehe machten das Winterwonderland komplett.",
    bild5: "assets/images/JägerHütte.PNG",
    description4: "Selbst die unsicheren Wege konnten die Magie nicht nehmen.",
    bild6: "assets/images/Nichts.PNG",
    bild7: "assets/images/ChiaraKomisch.PNG",
    bild8: "assets/images/Nichts.PNG",
    description5:
        "Nach dem anspruchsvollen Aufstieg auf den Leonberg wurden wir ausgiebig belohnt.",
    bild9: "assets/images/ChiaraWald.PNG",
    description6: "Die Aussicht genossen wir bei heißen Getränken und Snacks.",
    bild10: "assets/images/AussichtLeonberg.PNG",
    description7:
        "Nach unserer Rast machten wir uns schon bald auf den Rückweg, da wir versprochen hatten das Abendessen zu wuppen.\nNachdem Chiaras Handy plötzlich nur noch 2% anzeigte und sich dann mit einem Vibrieren verabschiedete, gab auch Linda’s Knochen den Geist auf. Grund dafür: die -14 Grad. Rückweg also ohne Navigation – Top!",
    bild11: "assets/images/WaldQuer.PNG",
    description8: "\n",
    bild12: "assets/images/HundLiegen.PNG",
    description9:
        "Mit einer von uns gezauberten Pizza neigte sich auch unser zweiter freier Tag dem Ende entgegen.",
    bild13: "assets/images/PizzaBayern.PNG",
    description14:
        "Haltet die Ohren steif!\nPfiat eich\n\nEure Chiara und Linda",
    bild14: "assets/images/3Könige.PNG",
    description10: "",
  ),
  BlogModel(
    ort: "Bayern",
    date: "10 Februar 2021",
    image: "assets/images/ChaostagStartbild.PNG",
    title: "Chaostag",
    description1:
        "Hidiho ihr da draußen,\n\nheute haben wir unseren ersten freien Tag richtig ausgenutzt und erstmal fett ausgeschlafen. So ziemlich direkt nach dem Aufstehen gab es dann schon Mittagessen. Geplant war ein gemütlicher, nicht allzu langer Spaziergang in das nahegelegene Dörfle Erlbach mit dem Austrian Shepherd Balu.",
    bild1: "assets/images/HundSchnee.PNG",
    description2:
        "Der Chaos-Tag begann, als wir die Tür zum Stall öffneten und gerade noch einen Zusammenstoß mit den frei herumlaufenden Eseln vermeiden konnten. Ein Blick in den hinteren Teil des Stalls ließ uns das Blut in den Adern gefrieren. Die Lamas waren ebenso ausgebüxt und lebten ihr best partylife.",
    bild2: "assets/images/Nichts.PNG",
    bild4: "assets/images/VieleLamas.PNG",
    bild3: "assets/images/Nichts.PNG",
    description3:
        "Gefeiert wurde nicht nur in den Gängen, sondern auch die Pferde-, Ziegen- und Eselboxen wurden besetzt. Linda versuchte innen die Lamas plus Anhang zu bändigen, während sie von draußen nur Chiaras Geschrei wahrnahm. Diese hatte alle Hände voll damit zu tun die 3 Hunde zu bändigen. Wisp und Sepp, die zwei anderen Hunde, waren eifersüchtig auf den auserwählten Balu, während dieser fast vor Ungeduld auf den Spaziergang explodierte.",
    bild5: "assets/images/Chewbacca.PNG",
    description4: "",
    bild6: "assets/images/Nichts.PNG",
    bild7: "assets/images/SchwarzWeißerHund.PNG",
    bild8: "assets/images/Nichts.PNG",
    description5:
        "Als die zwei Spezialisten das Ding mal wieder gerockt haben und alle Tiere wieder zuhause waren, ging es endlich los. Nach ein paar Sprinteinheiten mit Balu verdunkelt sich Chiaras Miene: „Linda, mein Handy ist weg!“, stammelte sie.\n\nAlso kehrten wir um und liefen die bisher zurückgelegte Strecke mit unserem Spürhund ab. Auf den letzten Metern fanden wir das arme Ding einsam und fröstelnd im Schnee liegen. Mit neuem Glück wagten wir einen zweiten Anlauf in Richtung Erlbach. Für die auf 20 Minuten ausgelegte Strecke brauchten wir aufgrund von Umwegen durch Wiesen und Wälder etwas länger.",
    bild9: "assets/images/SchneeWald.PNG",
    description6:
        "Nach 1,5 h haben es die zwei Armleuchten dann auch mal geschafft. In dem 1200-Seelen-Dorf, gönnten wir uns bei dem eigentlich schon geschlossenen Bäcker einen Gaumenschmaus. Aufgrund der Sprachbarriere zwischen dem Bäcker und Chiara blieb es spannend mit was sie das süße Lädchen verlässt. Heraus kam sie mit einer heißen Schokolade und einer köstlichen Vanilleschnecke.",
    bild10: "assets/images/LindaSnack.PNG",
    description7:
        "Gestärkt machten wir uns auf den Rückweg. Nach einer holprigen Wanderung über Äcker und Privatgrundstücke folgte der Höhepunkt des Tages. Als wir auf der anderen Straßenseite Sabine und Wisp sahen, gab es für Balu kein Halt mehr. Ohne Angst vor Verlusten zog er Chiara den Straßengraben hinunter. Sabine beobachtete das Geschehen aus 200m Entfernung. – Linda amüsierte sich prächtig und hörte nicht mehr auf zu lachen.",
    bild11: "assets/images/ChiaraAss.PNG",
    description8: "",
    bild12: "assets/images/Nichts.PNG",
    description9: "",
    bild13: "assets/images/Rutschspur.PNG",
    description14:
        "So ging der Chaos-Tag zu ende und wir fielen tot ins Bett.\n\nHaltet die Ohren steif!\nPfiat eich\n\nEure Chiara und Linda",
    bild14: "assets/images/Nichts.PNG",
    description10: "",
  ),
  BlogModel(
    ort: "Bayern",
    date: "08-09 Februar 2021",
    image: "assets/images/EPEStartbild.PNG",
    title: "Ein paar Eindrücke",
    description1:
        "Na ihr Schlawiner,\n\nhaben gerade nicht so viel Zeit für euch – chillen lieber mit unserer Gang.\n\nHier ein paar Eindrücke:",
    bild1: "assets/images/PunktLama.PNG",
    description2: "",
    bild2: "assets/images/Nichts.PNG",
    bild4: "assets/images/Nichts.PNG",
    bild3: "assets/images/LindaKatze.PNG",
    description3: "\n",
    bild5: "assets/images/ChiaraKatze.PNG",
    description4: "",
    bild6: "assets/images/Nichts.PNG",
    bild7: "assets/images/LindaSeitlich.PNG",
    bild8: "assets/images/Nichts.PNG",
    description5: "",
    bild9: "assets/images/ChiaraBaby.PNG",
    description6: "",
    bild10: "assets/images/Nichts.PNG",
    description7: "",
    bild11: "assets/images/ChiaraHund.PNG",
    description8: "\n",
    bild12: "assets/images/LindaKuss.PNG",
    description9: "\n",
    bild13: "assets/images/LindaHund.PNG",
    description14:
        "Haltet die Ohren steif!\nPfiat eich\n\nEure Chiara und Linda",
    bild14: "assets/images/Nichts.PNG",
    description10: "",
  ),
  BlogModel(
    ort: "Bayern",
    date: "07 Februar 2021",
    image: "assets/images/LEStartbild.PNG",
    title: "Lahme Ente",
    description1:
        "Hallöchen mit Öchen, \n\ndamit ihr uns nicht zu arg vermisst, hier ein kurzes Update. Am Sonntag haben wir den Stall das erste Mal zu zweit gewuppt. Überraschenderweise lief alles nach Plan und sogar den Durst der Lämmer haben wir gut gestillt.",
    bild1: "assets/images/ChiaraLämmer.PNG",
    description2:
        "Noch vor dem Mittagessen machten wir ein Spaziergang mit Manfred und zwei Girls aus dem Tierheim. Zwei Miniponys, zwei Esel und ein Lamahengst waren auch am Start.",
    bild2: "assets/images/LindaPony.PNG",
    bild4: "assets/images/Nichts.PNG",
    bild3: "assets/images/ChiaraPony.PNG",
    description3:
        "Linda’s Minipony war genau so ne lahme Ente wie sie selbst und so hingen sie immer etwas hinterher.\n\nNach einem geilen Mittagessen ging es mit einer Kutschfahrt weiter.",
    bild5: "assets/images/Nichts.PNG",
    description4: "",
    bild6: "assets/images/Nichts.PNG",
    bild7: "assets/images/Nichts.PNG",
    bild8: "assets/images/Nichts.PNG",
    description5: "Haltet die Ohren steif!\nPfiat eich",
    bild9: "assets/images/Nichts.PNG",
    description6: "Eure Chiara und Linda",
    bild10: "assets/images/Nichts.PNG",
    description7: "",
    bild11: "assets/images/LamaZahn.PNG",
    description8: "",
    bild12: "assets/images/Nichts.PNG",
    description9: "",
    bild13: "assets/images/Nichts.PNG",
    description14: "",
    bild14: "assets/images/Nichts.PNG",
    description10: "",
  ),
  BlogModel(
    ort: "Bayern",
    date: "06 Februar 2021",
    image: "assets/images/Wasserski.PNG",
    title: "Wasserski mit Eseln",
    description1:
        "Hallo liebe Fans, \n\nheute hat unser Arbeitstag ganz entspannt mit einem Spaziergang begonnen, da Zorro, einer der zwei Miniponys, eine Kolik hat und deshalb Bewegung braucht. Begleitet haben uns Mr. Big, das andere Minipony und die beiden Esel, Lola und Sanjo.",
    bild1: "assets/images/Landschaft.PNG",
    description2:
        "Naja es wären ja nicht wir, wenn es nicht einen kleinen Zwischenfall gegeben hätte. Nach einer dreiviertel Stunde mehr oder weniger entspanntem Laufen ging es los. 20 Rehe schossen direkt vor unserer Nase aus dem Wald. Unsere Esel ließ das nicht kalt. Sanjo, Linda’s Esel begann und wurde zu Usain Bolt. Lola, die Nachmacherin ließ nicht lange auf sich warten. Nicht zu vergessen, wir befanden uns auf einer suboptimalen Sprintstrecke. Schlamm, Wurzeln und Gefälle machten uns das Leben schwer. So schlitterten wir den Eseln hinterher in der einzigen Hoffnung den Strick nicht loszulassen und unseren Allerwertesten nicht im Matsch zu versenken. An eine ruhige, tiefe Stimme und die Worte „Ho“ und „Scheritt“ dachten wir im Traum nicht. So ließ Linda einen grellen Schrei los und Chiara, die Nachmacherin, ließ nicht lang auf sich warten. Doch wie man uns kennt, haben wir auch diese Situation gemeistert.",
    bild2: "assets/images/Plakat.PNG",
    bild4: "assets/images/Nichts.PNG",
    bild3: "assets/images/Nichts.PNG",
    description3: "Am Ende hatten wir uns alle wieder lieb.",
    bild5: "assets/images/ChiaraEsel.PNG",
    description4: "",
    bild6: "assets/images/Nichts.PNG",
    bild7: "assets/images/LindaEsel.PNG",
    bild8: "assets/images/Nichts.PNG",
    description5:
        "Auf den Schreck folgte dann noch ein Kamelspaziergang - Oh Backe!",
    bild9: "assets/images/Wasserski.PNG",
    description6:
        "In dem Irrglauben Manfred und Susan führen die Riesenoschis Nojan und Akai und wir Armleuchten trotten lediglich hinterher, liefen wir los. \nKomischerweise hielten wir nach zwei Minuten die Stricke in der Hand. \n\nBevor Chiara die zweite Hand um den Strick legen konnte, hatte sie bereits die Schnauze ihres Kollegen im Nacken. Die Anweisung Manfred‘s: „Brust raus, ihr seid der Boss“, nahmen wir uns zu Herzen und kamen schlussendlich ganz gut klar mit unseren Riesen.",
    bild10: "assets/images/ChiaraKamel.PNG",
    description7:
        "Kleiner side fact: \nAuf einem Kamel zu hocken ist bequemer wie in so manchem Bett. Mit der Ausnahme, dass Chiara es noch nicht geschafft hat sich im Bett ihren Po zu zerren. \n\nGroßer side fact: \nMännliche Kamele beißen sich gegenseitig die Eier ab. So viel zu Pflanzenfresser...",
    bild11: "assets/images/Kamel.PNG",
    description8:
        "Am Abend hatten wir sturmfrei und mächtig Kohldampf. Nach einem köstlichem Abendessen ließen wir den Abend bei Wein, Billard und Musik zu dritt ausklingen.",
    bild12: "assets/images/Billard.PNG",
    description9:
        "Haltet die Ohren steif! \nPfiat eich \n\nEure Chiara und Linda",
    bild13: "assets/images/komischesSelfie.PNG",
    description14: "",
    bild14: "assets/images/Nichts.PNG",
    description10: "",
  ),
  BlogModel(
    ort: "Bayern",
    date: "05 Februar 2021",
    image: "assets/images/Der_erste_Tag.png",
    title: "Der erste Tag",
    description1:
        "Unsere Angst den Umbreit/Konzelmann-Arbeitszeiten nicht zu entkommen hat sich zum Glück nicht bestätigt, unser Arbeitsalltag beginnt erst um 9. \nMorgens brauchen zuerst alle Tiere Wasser und ne ordentliche Portion Streicheleinheiten. Vor allem die Lämmer, welche größtenteils mit der Flasche aufgezogen wurden schreien nach Liebe. Die Lämmer sind so goldig, dass wir aus dem Grinsen nicht mehr rauskamen. Trotzdem üben wir noch unser perfektes Zahnpastalächeln.",
    bild1: "assets/images/Linda+Schaf.png",
    description2: "Auch die Kiefermuskeln wachsen schon",
    bild2: "assets/images/Chiara+Schaf.png",
    bild4: "assets/images/Nichts.PNG",
    bild3: "assets/images/Nichts.PNG",
    description3:
        "Danach kommt wortwörtlich die Scheißarbeit – das Misten. Vorallem die Pferdeäpfel von Wiggl und Wotan, den zwei Kaltblüter, bringen unseren Bizeps zum brennen.",
    bild5: "assets/images/Pferde.PNG",
    description4: "",
    bild6: "assets/images/Nichts.PNG",
    bild7: "assets/images/LindaStall.PNG",
    bild8: "assets/images/Nichts.PNG",
    description5:
        "Mittagessen gibt es immer um 12 Uhr, welches meistens Manfred zubereitet und bis jetzt immer sehr lecker war. \nUm 3 Uhr ging es mit unserem ersten Lamaspaziergang weiter. Linda’s Lama wollte entweder stehen, rennen oder am Vordermann schnüffeln, während Chiara‘s beim ersten Auto meinte komplett durchzudrehen – dat lief ja mal wieder glatt.",
    bild9: "assets/images/BeideLama.PNG",
    description6: "",
    bild10: "assets/images/ChiaraLama.PNG",
    description7:
        "Das Abendessen ließ unsere Münder brennen bis sich Chiara dazu entschloss ihren Mund mit einem Glas Milch zu löschen. \n\nHaltet die Ohren steif! \nPfiat eich \n\nEure Chiara und Linda \n\nPS. : Hier ist es etwas frisch.",
    bild11: "assets/images/Nichts.PNG",
    description8: "",
    bild12: "assets/images/Nichts.PNG",
    description9: "",
    bild13: "assets/images/Nichts.PNG",
    description14: "",
    bild14: "assets/images/Nichts.PNG",
    description10: "",
  ),
  BlogModel(
    ort: "Bayern",
    date: "04 Februar 2021",
    image: "assets/images/Startbild.png",
    title: "Anreise",
    description1:
        "Um 11:15 Uhr ging's los – naja eigentlich schon abends, als Chiara Linda verzweifelt anrief und panisch fragte: Samal, bekommst du eigentlich dein Rucksack aufgesetzt?! Doch nach ein paar Übungseinheiten am Abend und den ersten schwankenden Schritten war auch schon unser erstes Problem einigermaßen beseitigt. \nAm Bahnhof angekommen fingen wir uns einige komische Blicke ein. Klar, wohin will man denn auch mit einem riesen Tourenrucksack während Corona.",
    bild1: "assets/images/Anreise1.png",
    bild2: "assets/images/ChiaraBahnhof.PNG",
    description2:
        "Doch Insgesamt verliefen die Zugfahrten, bis auf ein paar Horrorgedanken (Angst gegessen zu werden/erst gar nicht abgeholt zu werden) reibungslos, worauf wir natürlich auch ein bisschen stolz sind. Okay, zugegeben, vor jedem Umstieg hatten wir doch etwas Bangel, ob wir unseren Rucksack gestemmt bekommen. Deshalb waren wir jedes Mal schon eine viertel Stunde früher zum Aussteigen bereit. Aber pssht!!",
    description3:
        "In Neuötting angekommen wurden wir überraschenderweise von einer anderen Workawayerin, namens Susan aus Stuttgart, abgeholt. Die Sorge sie nicht zu finden war verflogen, als wir sie schon im Zug sahen, dass sie direkt vor unserer Zugtür stand. Als Susan in die Hoffeinfahrt einbog begrüßten uns direkt 25 Lamas.",
    bild3: "assets/images/LindaZug.PNG",
    bild4: "assets/images/Nichts.PNG",
    bild5: "assets/images/Lama.PNG",
    description4:
        "Auf dem Hof angekommen wurde uns direkt unser Kinderzimmer gezeigt, in welchem wir uns pudelwohl fühlen.",
    bild6: "assets/images/LindaBett.PNG",
    bild7: "assets/images/Nichts.PNG",
    bild8: "assets/images/ChiaraBett.PNG",
    description5:
        "Danach ging es direkt in den Stall. Nach einem Begrüßungskuss der drei Hunde, warteten schon jegliche Tiere auf uns – von Miniponys über Lämmer bis hin zu Kamelen – alles dabei.  Der beeindruckenste Moment des Tages war unser erster Blick auf die Kamele. – Was für riesen Oschis! Bisschen Schiss gegessen zu werden hatten wir auch hier wieder.",
    bild9: "assets/images/ganzesLama.PNG",
    description6:
        "Weiter ging es mit der allseits bekannten Tollpatschigkeit von Chiara, die erst mal den Eimer Wasser über sich gekippt hat, anstatt ihn den durstigen Lämmern zu geben.",
    bild10: "assets/images/ChiaraSocke.PNG",
    description7:
        "Am Abend hatten wir uns ein ordentliches Vesper mit super leckerem Selbstgemachten Brot (Knoblauch, Anis – und Pfefferbrot) von unserem Gastvater Manfred verdient. Das kleine Kreuzverhör mit Manfred wurde durch den leckersten Weißwein, den wir je getrunken haben, erträglich gemacht. – Nein Spaß, natürlich hätten wir uns auch ohne wohlgefühlt. Bei den über 200 Workawayern, die bereits bei Manfred und Sabine waren, gab es natürlich auch witzige Geschichten zu erzählen, die zu vielen Gelächtern führten. Wir sind schon sehr gespannt was uns die nächsten Tage erwartet. \n\nHaltet die Ohren steif! \nPfiat eich \n\nEure Chiara und Linda",
    bild11: "assets/images/LindaZimmer.PNG",
    description8: "",
    bild12: "",
    description9: "",
    bild13: "",
    description14: "",
    bild14: "",
    description10: "",
  ),
];
